### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by Valecant**
## Proposed changes

Describe the big picture of your changes here to communicate to the
maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to link to
that issue.

## Types of changes

What types of changes does your code introduce to the project: _Put
an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation (improve documentation)
- [ ] Continuous Integration (functionality that improve automation or testing)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after
creating the PR. If you're unsure about any of them, don't hesitate to
ask. We're here to help! This is simply a reminder of what we are going
to look for before merging your code._

- [ ] I have read the [CONTRIBUTING][contrib] doc
- [ ] I have signed the [Contributor License Agreement][cla]
- [ ] I have updated the [RELEASE NOTES][release]
- [ ] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion
by explaining why you chose the solution you did and what alternatives
you considered, etc...

[cla]: https://raw.githubusercontent.com/orchestracities/auth-management-ui/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/auth-management-ui/blob/master/CONTRIBUTING.md
    "Contributing to auth-management-ui"
[release]: https://github.com/orchestracities/auth-management-ui/blob/master/RELEASE_NOTES.md
    "auth-management-ui Release Notes"

### CODE REVIEW

**Review by Cerfoglg — APPROVED** [review]
LGTM

**Comment by chicco785** [comment]
not sure if I am doing something wrong, but this is what is see using this branch and Iphone 12 size
image
image
image

**Review by chicco785 — CHANGES_REQUESTED** [review]
one mobile phones ui is still not usable

**Comment by Valecant** [comment]
> one mobile phones ui is still not usable
what part of the UI?

**Comment by Valecant** [comment]
> not sure if I am doing something wrong, but this is what is see using this branch and Iphone 12 size image image image
Schermata 2022-07-25 alle 13 30 21

have you cleaned up everything before testing?.
looks like to me the branche before the changes:

**Comment by chicco785** [comment]
> > Schermata 2022-07-25 alle 13 30 21
> 
> have you cleaned up everything before testing?. looks like to me the branche before the changes:

indeed, after cleaning the build, the view is now as in your screenshot, we should still:
- reduce the title size (is really too much in mobile screen)
localhost_3000_Policy(iPhone 12 Pro) (1)

- reduce space when filters go on multiple lines
localhost_3000_Policy(iPhone 12 Pro)

**Comment by chicco785** [comment]
> * reduce the title size (is really too much in mobile screen)
>   localhost_3000_Policy(iPhone 12 Pro) (1)

maybe this is a good solution: https://mui.com/material-ui/customization/theming/#responsivefontsizes-theme-options-theme

**Review by chicco785 — APPROVED** [review]

**Pull request merged**
