### PR TITLE
Packages migration (#136)

### PR DESCRIPTION
**Pull request by Valecant**
## Proposed changes

Remove packages that are not longer maintained and update the syntax to the newer version of apollo 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Documentation (improve documentation)
- [ ] Continuous Integration (functionality that improve automation or testing)
- [ ] Breaking change (fix or feature that would cause existing
      functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING][contrib] doc
- [x] I have signed the [Contributor License Agreement][cla]
- [x] I have updated the [RELEASE NOTES][release]
- [x] I have added tests that prove my fix is effective or that my
      feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in
      downstream modules

## Further comments

Of course this is a restoration and not a revolution of what we are usiing

[cla]: https://raw.githubusercontent.com/orchestracities/auth-management-ui/master/individual_cla.pdf
    "Martel Open Source Software Individual Contributor License Agreement"
[contrib]: https://github.com/orchestracities/auth-management-ui/blob/master/CONTRIBUTING.md
    "Contributing to auth-management-ui"
[release]: https://github.com/orchestracities/auth-management-ui/blob/master/RELEASE_NOTES.md
    "auth-management-ui Release Notes"

### CODE REVIEW

**Review by c0c0n3 — COMMENTED** [review]
great job, are we going to upgrade react to v18 too? or should we leave it for now?

**Comment by Valecant** [comment]
> great job, are we going to upgrade react to v18 too? or should we leave it for now?

upgraded to latest version of every library (react 18.2 too).
I rework to the map was needed and a new library for the JSON editor too (the one that we used was linked to react 17 or 16)

**Review by c0c0n3 — COMMENTED** [review]
oidc trusted domains should be empty lists for now?

**Comment by c0c0n3** [comment]
note. `public/OidcServiceWorker.js` gets generated automatically on upgrading the `axa-fr/react-oidc` lib.

**Review by c0c0n3 — APPROVED** [review]
great, thx!!

**Pull request merged**
